{% set name = "pydistcheck" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydistcheck-{{ version }}.tar.gz
  sha256: 1fae246e4256501f0334dc74d9c8683916ef2f6c55e5ac6eed73bbd013e4f272

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pydistcheck = pydistcheck.cli:check
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click
    - tomli

test:
  imports:
    - pydistcheck
  commands:
    - pip check
    - pydistcheck --help
  requires:
    - pip

about:
  home: https://github.com/jameslamb/pydistcheck
  summary: Inspect Python package distributions and raise warnings on common problems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jameslamb
