{% set name = "pydistcheck" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydistcheck-{{ version }}.tar.gz
  sha256: 31aa5697511a08b64364c930bb844dacda433f39a24b4d7d210a82796883f38a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pydistcheck = pydistcheck.cli:check
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=75.0
  run:
    - python >={{ python_min }}
    - click >=8.0
    - tomli >=1.1.1
    # zstandard is optional in wheels, but requiring it here
    # because it's required to run pydistcheck on conda packages
    - zstandard >=0.22.0

test:
  imports:
    - pydistcheck
  commands:
    - pip check
    - pydistcheck --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jameslamb/pydistcheck
  summary: Inspect Python package distributions and raise warnings on common problems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jameslamb
