{% set name = "pydistcheck" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydistcheck-{{ version }}.tar.gz
  sha256: a89035cc32c18a3b9e2b1814dfaf53d18fa30c6190d1d248414933b7f01ba1a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pydistcheck = pydistcheck.cli:check
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click
    - tomli

test:
  imports:
    - pydistcheck
  commands:
    - pip check
    - pydistcheck --help
  requires:
    - pip

about:
  home: https://github.com/jameslamb/pydistcheck
  summary: Inspect Python package distributions and raise warnings on common problems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jameslamb
